config:
  namespace: "itsma-clienta"
  ESM_NAMESPACE: "itsma-clienta"
  version: "24.4"
  registry: "registry.example.com"
  registry_server: "registry.example.com"
  nfs_server: "nfs.internal.com"
  username: "admin"
  password: "changeme"
  image_secret_name: "regcred"

stages:
  - name: "Preparation"
    steps:
      - id: "health_check"
        title: "SMAX Health Check"
        notes: "Ensure all pods are in 2/2 or 1/1 Running state before starting."
        command: "kubectl get pods -n {{namespace}}"
        done: false
        userNotes: ""
      
      - id: "create_secret"
        title: "Create Docker Registry Secret"
        notes: "Create secret for pulling images from private registry."
        command: "kubectl create secret docker-registry <image_secret_name> --docker-username=<username> --docker-password=<password> --docker-server=<registry_server> -n <ESM_NAMESPACE>"
        done: false
        userNotes: ""
      
      - id: "backup_db"
        title: "External DB Backup"
        notes: "Backup BoB, SmartAnalytics, and IdM databases manually."
        command: "pg_dump -h {{nfs_server}} -U postgres bo_db > smax_backup_$(date +%Y%m%d).sql"
        done: false
        userNotes: ""

  - name: "Upgrade"
    steps:
      - id: "apply_upgrade"
        title: "Apply Suite Upgrade"
        notes: "This triggers the actual version change in OMT."
        command: "./upgrade.sh -n {{namespace}} -v {{version}}"
        done: false
        userNotes: ""
      
      - id: "monitor_upgrade"
        title: "Monitor Upgrade Progress"
        notes: "Watch pods restart and come back online."
        command: "kubectl get pods -n <ESM_NAMESPACE> -w"
        done: false
        userNotes: ""

  - name: "Verification"
    steps:
      - id: "verify_version"
        title: "Verify SMAX Version"
        notes: "Confirm the upgrade was successful."
        command: "kubectl get pods -n {{namespace}} -o jsonpath='{.items[0].spec.containers[0].image}'"
        done: false
        userNotes: ""
      
      - id: "smoke_tests"
        title: "Run Smoke Tests"
        notes: "Test basic functionality: login, create ticket, etc."
        command: ""
        done: false
        userNotes: ""
