config:
  namespace: "itsma-clientb"
  ESM_NAMESPACE: "itsma-clientb"
  version: "24.4"
  registry: "registry.example.com"
  registry_server: "registry.example.com"
  nfs_server: "nfs.client-b.com"
  username: "sysadmin"
  password: "password123"
  image_secret_name: "registry-secret"

stages:
  - name: "Pre-Upgrade Validation"
    steps:
      - id: "check_resources"
        title: "Check Cluster Resources"
        notes: "Verify sufficient CPU and memory available."
        command: "kubectl top nodes"
        done: true
        userNotes: "**Completed on 2024-01-15**\n\nAll nodes have sufficient resources:\n- Node 1: 40% CPU, 60% Memory\n- Node 2: 35% CPU, 55% Memory"
      
      - id: "check_storage"
        title: "Verify Storage Availability"
        notes: "Ensure adequate storage for upgrade."
        command: "kubectl get pvc -n <ESM_NAMESPACE>"
        done: true
        userNotes: ""
  
  - name: "Backup"
    steps:
      - id: "backup_config"
        title: "Backup Configuration"
        notes: "Export current configuration files."
        command: "kubectl get configmaps -n {{namespace}} -o yaml > backup-configmaps.yaml"
        done: false
        userNotes: ""
      
      - id: "backup_db"
        title: "Database Backup"
        notes: "Full database dump before upgrade."
        command: "pg_dump -h {{nfs_server}} -U postgres bo_db > smax_backup.sql"
        done: false
        userNotes: ""

  - name: "Upgrade Execution"
    steps:
      - id: "apply_upgrade"
        title: "Apply Upgrade Package"
        notes: "Execute upgrade script with version parameter."
        command: "./upgrade.sh -n <ESM_NAMESPACE> -v {{version}}"
        done: false
        userNotes: ""
      
      - id: "wait_for_completion"
        title: "Wait for Upgrade Completion"
        notes: "Monitor until all pods are running."
        command: "kubectl wait --for=condition=Ready pods --all -n {{namespace}} --timeout=30m"
        done: false
        userNotes: ""

  - name: "Post-Upgrade Testing"
    steps:
      - id: "health_check"
        title: "Health Check"
        notes: "Verify all services are healthy."
        command: "kubectl get pods -n <ESM_NAMESPACE>"
        done: false
        userNotes: ""
      
      - id: "functional_test"
        title: "Functional Testing"
        notes: "Test core functionality."
        command: ""
        done: false
        userNotes: ""
      
      - id: "performance_test"
        title: "Performance Validation"
        notes: "Check response times and throughput."
        command: ""
        done: false
        userNotes: ""
